name: Bearer PR Check

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  rule_check:
    runs-on: [self-hosted]
    if: ${{ false || github.actor != 'github-actions[bot]' }}
    env:
      BEARER_DIFF_BASE_BRANCH: master
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Bearer
        uses: bearer/bearer-action@v2
        with:
          diff: true
          scanner: "secrets,sast"
          format: rdjson
          output: rd.json
          exit-code: 0
      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat rd.json | reviewdog -f=rdjson -reporter=github-pr-review
